# Setup
title:               re:coding
tagline:             'since 2013'
description:         ''
url:                 https://leemiroo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Miru LEE
  url:               https://github.com/leemiroo
  email:             leemiroo.dev@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
